// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// cIsdbscan
Rcpp::List cIsdbscan(SEXP data, int k, int batch_size);
RcppExport SEXP _ISDBSCAN_cIsdbscan(SEXP dataSEXP, SEXP kSEXP, SEXP batch_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type batch_size(batch_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(cIsdbscan(data, k, batch_size));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ISDBSCAN_cIsdbscan", (DL_FUNC) &_ISDBSCAN_cIsdbscan, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_ISDBSCAN(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
