// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// isdbscan
Rcpp::List isdbscan(SEXP data, int k, int batch_size, bool stratif, bool approximate, bool transpose);
RcppExport SEXP _ISDBSCAN_isdbscan(SEXP dataSEXP, SEXP kSEXP, SEXP batch_sizeSEXP, SEXP stratifSEXP, SEXP approximateSEXP, SEXP transposeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type batch_size(batch_sizeSEXP);
    Rcpp::traits::input_parameter< bool >::type stratif(stratifSEXP);
    Rcpp::traits::input_parameter< bool >::type approximate(approximateSEXP);
    Rcpp::traits::input_parameter< bool >::type transpose(transposeSEXP);
    rcpp_result_gen = Rcpp::wrap(isdbscan(data, k, batch_size, stratif, approximate, transpose));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ISDBSCAN_isdbscan", (DL_FUNC) &_ISDBSCAN_isdbscan, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_ISDBSCAN(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
