# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'
#' isdbscan
#'
#'@param dataset numeric matrix or integer matrix or HDF5Matrix
#'@param k the number of clusters
#'@param batch_size the size of the mini batches
#'@details
#'This function performs the isdbscan algorithm over the specified dataset.
#'
#' @export
isdbscan <- function(data, k, batch_size, stratif, approximate, transpose) {
    .Call(`_ISDBSCAN_isdbscan`, data, k, batch_size, stratif, approximate, transpose)
}

